### PR TITLE
Split unit from description

### LINKED ISSUE #52: Store unit outside title/description
Currently the unit of a parameter is store inside the title or description. For example [Initial mixed-layer specific humidity [kg kg-1]](https://github.com/classmodel/class-web/blob/fa4a9c5b4f435382f4a26275ed31f41b22465c45/packages/class/src/config.ts#L21).

It would be nice if the unit could be stored separately so it be used as suffix in input field like https://mui.com/material-ui/react-text-field/#input-adornments or for unit conversions or check unit during calculations.

From https://github.com/classmodel/class-web/pull/44#discussion_r1786167045

Inside JSON schema we could 
1. add an `unit` keyword or 
2. add a extra property called `<parameter_name>_unit` for example `theta_0_unit`.

We could also look at some library (like https://pint.readthedocs.io/, but in js/ts) to help with unit validation/conversion.

### PR DESCRIPTION
**Pull request by sverhoeven**
Add unit keyword to json schema validator + in json schema add unit to theta_0 as example + render unit in input field

Fixed #52

localhost_3000_ (2)

TODO

- [x] test unit in json schema, used theta_0
- [x] ajv unit aware
- [x] move all units from description to unit keyword

### CODE REVIEW

**Review by Peter9192 — COMMENTED** [review]
Looks good! Now need to move all units to separate fields.

Should we .gitignore config.ts and/or stop it from being tracked? Maybe as part of "generating it as part of the build"

**Comment by sverhoeven** [comment]
Also it would be nice to render unit with mathml or subscript/superscript.

**Review by Peter9192 — APPROVED** [review]
Nice work. Not sure if we want to keep or discard `[-]`, but we could bring it back if needed.

Unit less parameters now standout because the do not have a gray box in the input field.

**Comment by sverhoeven** [comment]
> Nice work. Not sure if we want to keep or discard `[-]`, but we could bring it back if needed.

Unit less parameters now standout because the do not have a gray box in the input field.

**Pull request merged**
