### PR TITLE
Make session share button + persist to local storage

### LINKED ISSUE #20: Save app state in local storage

### PR DESCRIPTION
**Pull request by sverhoeven**
Refs #61
Fixes #20

Moves ShareButton from experiment to whole app

TODO
- [x] Handle inline todos
- [x] implement code for failing e2e test

### CODE REVIEW

**Comment by sverhoeven** [comment]
Uploading big experiment twice causes very slow setExperiments calls

```
Running reference: 17.72705078125 ms
store.ts:80 Store reference output: 2383.742919921875 ms
store.ts:91 Running permutation 0: 12.35986328125 ms
store.ts:100 Store permutation 0 output: 2659.326904296875 ms
store.ts:91 Running permutation 1: 14.31591796875 ms
store.ts:100 Store permutation 1 output: 2904.865966796875 ms
store.ts:91 Running permutation 2: 11.546142578125 ms
store.ts:100 Store permutation 2 output: 2997.45703125 ms
store.ts:91 Running permutation 3: 12.759033203125 ms
store.ts:100 Store permutation 3 output: 3252.910888671875 ms
store.ts:91 Running permutation 4: 11.48193359375 ms
store.ts:100 Store permutation 4 output: 3640.27001953125 ms
store.ts:91 Running permutation 5: 14.137939453125 ms
store.ts:100 Store permutation 5 output: 4071.215087890625 ms
store.ts:91 Running permutation 6: 19.54296875 ms
store.ts:100 Store permutation 6 output: 5085.98583984375 ms
store.ts:91 Running permutation 7: 21.6650390625 ms
store.ts:100 Store permutation 7 output: 5598.215087890625 ms
store.ts:91 Running permutation 8: 12.47607421875 ms
store.ts:100 Store permutation 8 output: 5926.547119140625 ms
store.ts:91 Running permutation 9: 14.406005859375 ms
store.ts:100 Store permutation 9 output: 6255.922119140625 ms
store.ts:91 Running permutation 10: 16.05322265625 ms
store.ts:100 Store permutation 10 output: 6309.295166015625 ms
store.ts:91 Running permutation 11: 6.177978515625 ms
store.ts:100 Store permutation 11 output: 8132.091064453125 ms
store.ts:91 Running permutation 12: 7.419921875 ms
store.ts:100 Store permutation 12 output: 8185.593017578125 ms
store.ts:91 Running permutation 13: 21.483154296875 ms
```

Fixing by storing outputs outside store.

**Comment by sverhoeven** [comment]
To test making too big share link I first had to make a big config, for that I made a sweep button.

localhost_3000_ (3)
localhost_3000_ (4)

**Comment by sverhoeven** [comment]
> Uploading big experiment twice causes very slow setExperiments calls
> 
> ```
> Running reference: 17.72705078125 ms
> store.ts:80 Store reference output: 2383.742919921875 ms
> store.ts:91 Running permutation 0: 12.35986328125 ms
> store.ts:100 Store permutation 0 output: 2659.326904296875 ms
> store.ts:91 Running permutation 1: 14.31591796875 ms
> store.ts:100 Store permutation 1 output: 2904.865966796875 ms
> store.ts:91 Running permutation 2: 11.546142578125 ms
> store.ts:100 Store permutation 2 output: 2997.45703125 ms
> store.ts:91 Running permutation 3: 12.759033203125 ms
> store.ts:100 Store permutation 3 output: 3252.910888671875 ms
> store.ts:91 Running permutation 4: 11.48193359375 ms
> store.ts:100 Store permutation 4 output: 3640.27001953125 ms
> store.ts:91 Running permutation 5: 14.137939453125 ms
> store.ts:100 Store permutation 5 output: 4071.215087890625 ms
> store.ts:91 Running permutation 6: 19.54296875 ms
> store.ts:100 Store permutation 6 output: 5085.98583984375 ms
> store.ts:91 Running permutation 7: 21.6650390625 ms
> store.ts:100 Store permutation 7 output: 5598.215087890625 ms
> store.ts:91 Running permutation 8: 12.47607421875 ms
> store.ts:100 Store permutation 8 output: 5926.547119140625 ms
> store.ts:91 Running permutation 9: 14.406005859375 ms
> store.ts:100 Store permutation 9 output: 6255.922119140625 ms
> store.ts:91 Running permutation 10: 16.05322265625 ms
> store.ts:100 Store permutation 10 output: 6309.295166015625 ms
> store.ts:91 Running permutation 11: 6.177978515625 ms
> store.ts:100 Store permutation 11 output: 8132.091064453125 ms
> store.ts:91 Running permutation 12: 7.419921875 ms
> store.ts:100 Store permutation 12 output: 8185.593017578125 ms
> store.ts:91 Running permutation 13: 21.483154296875 ms
> ```
> 
> Fixing by storing outputs outside store.

`const outputs = []` is now used everywhere, still have some performance problems see https://github.com/classmodel/class-web/blob/c9eaeadc2b4dbde32a136d4e568055a0c52be269/apps/class-solid/src/lib/store.ts#L90-L93

**Comment by sverhoeven** [comment]
Fixes #63 

localhost_3000_ (5)

or when a experiment is present the + button will show in dialog.

**Comment by sverhoeven** [comment]
Rollback outputs premature optimization

**Review by Peter9192 — APPROVED** [review]
Reviewed interactively

**Comment by sverhoeven** [comment]
Hmm, with outputs back in store, adding the permutation sweep, the ui is slower. Duplicating experiment is even slower.
Might want to revert aac745a1c45af6f55f7be0eb077f0f9be2f158c6 to improve performance a bit.

**Pull request merged**
