### PR TITLE
Vertical profiles

### LINKED ISSUE #23: Add plot types for vertical profiles
both standard z-axis and skew-t/log-p diagrams, e.g. like those on windy.

For skew-t see   https://github.com/rittels/windy-plugin-radiosonde and https://www.npmjs.com/package/skewt-plus

### PR DESCRIPTION
**Pull request by Peter9192**
Refs #23 

To do:

- [x] Plot vertical profiles
- [x] Add axes
- [x] Nicer axis extents/ticks
- [x] Render all permutations of experiment
- [x] Render more than one experiment
- [x] Add legend
- [x] Add color cycling
- [ ] Tooltip on hover 
  - [x] Simply use SVG title element. But only works if mouse is exactly over path.
  - [ ] Add relevant data to tooltip content
  - [ ] Separate profile plot type with three straight lines rather than 4 connected points would give better tooltip content
- [x] Styling/font similar to SolidUI/Charts
  - [x] Tinkered with font family/size/weight/letter spacing etc now mostly similar
  - [x] For now stick with fixed axes and no grid lines as in chart.js, but open for opions.
- [x] Axis labels
- [ ] Make it possible to select variable
- [ ] Make it possible to select time (playback controls?)
- [x] Reuse own component in favour of solidui/chart for timeseries as well
  - [ ] This makes the app much slower; can we optimize?
  - [x] Reduce history interval to 10 minutes instead of 1 minute; somewhat better but still not great
  - [x] Remove dead code / unneeded dependencies (chart.js, chart component)
  - [x] Fix playwright test: if we stick with this, the canvas is gone, so we cannot screenshot it
- [x] Make reactive (if data changes, update plot)
- [ ] Responsive width/height (note: currently timeseries plot also not responsive)
- [x] Verify that `gammaq`/`gammatheta` always available
- [ ] Add skew-T/log-p plots (new PR)
- [x] Move buttons to card header
- [ ] What should be the default height? (currently simply extending profiles by 400m)
- [ ] Do we want to modify units, e.g. from kg/kg to g/kg for more readable digits? Or time in hours/minuts rather than seconds?
- [x] Make typecheck happy

image

### CODE REVIEW

**Comment by Peter9192** [comment]
Multiple options to import from d3:

- `import * as d3 from "d3";`
- `import {select, selectAll} from "d3";`
- `import {mean, median} from "d3-array";`

What I like about the first option is that the namespace is repeated in the code, e.g. `const x = d3.scaleLinear(...)`
What I like about the first and second is that I don't have to care about which function comes from which submodule
However, not sure if tree shaking works well enough for options 1 and 2.

**Comment by sverhoeven** [comment]
> Multiple options to import from d3:
> 
> * `import * as d3 from "d3";`
> * `import {select, selectAll} from "d3";`
> * `import {mean, median} from "d3-array";`
> 
> What I like about the first option is that the namespace is repeated in the code, e.g. `const x = d3.scaleLinear(...)` What I like about the first and second is that I don't have to care about which function comes from which submodule However, not sure if tree shaking works well enough for options 1 and 2.

Solid start uses https://esbuild.github.io/api/#tree-shaking, which can handle the those options.  Its a matter of taste, I prefer option 1 or 2 as my IDE writes the imports.

**Comment by Peter9192** [comment]
> * import * as d3 from "d3";

I went with option 1.

**Comment by Peter9192** [comment]
Rebased changes of this branch onto the latest master.

**Comment by Peter9192** [comment]
Question: should we hardcode the upper limit of the profiles? If so, to what value? And if not: how do we determine the end of the free troposphere lapse rate line?

**Comment by Chiil** [comment]
If you define a profile as a piecewise linear function, you can extend the last one to a very large number (`1e5` or so) which the BL will never reach

**Comment by Peter9192** [comment]
> If you define a profile as a piecewise linear function, you can extend the last one to a very large number (`1e5` or so) which the BL will never reach
>  

Sure, but what should be the limits of the (default) plots be?

**Comment by Peter9192** [comment]
For distinguishing experiments/runs, we could:

- Cycle colors to distinguish reference/permutation runs within a single experiment
- Cycle line styles to distinguish between experiments

**Review by sverhoeven — APPROVED** [review]
Nice, works for me. 

Fixed the ts errors for you, but with presets in #61 we can make it better

Can we merge as is and convert open todos to issues?

**Pull request merged**
