### PR TITLE
Move cli to into class package that can be published to npmjs.com

### PR DESCRIPTION
**Pull request by sverhoeven**
Follow of #57 

Bin in package,json is also known as package executables or package binaries.

JSR and bin does not work in same package as installing the package from JSR is missing bin entry.

TODO

- [x] Dev version working
- [x] Production version working
    - [x] Merge #66 and publish class package to jsr
    - [x] Make sure packaged cli depends on correct class package from npmjs, currently is doesnt, see comment below
    - [x] Publish cli package to npmjs
    - [x] Run `npx @classmodel/cli config.json `

### CODE REVIEW

**Comment by sverhoeven** [comment]
Maybe setting [alias](https://pnpm.io/workspaces#referencing-workspace-packages-through-aliases) will help.

**Comment by sverhoeven** [comment]
> Maybe setting [alias](https://pnpm.io/workspaces#referencing-workspace-packages-through-aliases) will help.

That does not work because then someone using the cli will need to add `@jsr:registry=https://npm.jsr.io` their .npmrc file. So I think its better if we switch to the publishing of `@classmodel/class`  from jsr to npmjs. 
This will make it also easier to use the package as a dependency.

**Comment by Peter9192** [comment]
Tried running `pnpm i` at top level of repo, now gives:
```
Failed to create bin at /home/peter/classmodel/class-web/apps/class-solid/node_modules/.bin/class. ENOENT: no such file or directory, open '/home/peter/classmodel/class-web/packages/class/dist/cli.js'
...
Failed to create bin at /home/peter/classmodel/class-web/apps/class-solid/node_modules/.bin/class. ENOENT: no such file or directory, open '/home/peter/classmodel/class-web/apps/class-solid/node_modules/@classmodel/class/dist/cli.js'
```

**Comment by sverhoeven** [comment]
Those are warnings, after a `pnpm build` or `pnpm dev` the warnings should not show.

**Pull request merged**
